# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

upx:
  - enabled: true
    goos: [linux]
    compress: best
    lzma: true

nfpms:
  - maintainer: Marco98
    description: "Proxy RSS-Podcast-Clients to yt-dlp"
    homepage: https://github.com/Marco98/ytpodproxy
    license: MIT
    formats:
      - deb
      - rpm

dockers:
  - dockerfile: Containerfile
    image_templates:
      - "ghcr.io/marco98/ytpodproxy:{{ .Tag }}"
      - "ghcr.io/marco98/ytpodproxy:latest"
