# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v4

      - name: Setup Python
        uses: https://github.com/actions/setup-python@v3

      - name: Run pre-commit
        uses: https://github.com/pre-commit/action@v3.0.1
